### ISSUE TITLE
Update apt-get install commands to new syntax

### ISSUE THREAD

**Issue by inghamn** [City-of-Bloomington/ansible-role-graylog-sidecar#2]
The old way of doing apt with-items is deprecated.  The new way is to declare a variable for all the package names.

## New style for apt-get install
```YAML
- name: "Install Dependencies"
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - "postgis"
```

## Old, deprecated style
```YAML
- name: "Install Dependencies"
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - "postgis"
```

**Comment by sethCOB** [comment]
Now there's an even new-newer way to declare multi-package installs with ansible! Updated the method in b032d2cdedaede4a74d8c4167f642c8cc0d91893
```
- name: "Install Dependencies"
  apt:
    name: ['software-properties-common', 'apt-transport-https']
    state: present
```
